spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nexus}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.example.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
jwt:
  secret: ${JWT_SECRET:defaultSecret}
  expiration: 86400
cloud:
  storage:
    url: "https://mock-cloud-storage.com/"
